version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: katbin_pg
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: katbin
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: