//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "custom(\"citext\")")]
    pub email: String,
    pub hashed_password: String,
    pub confirmed_at: Option<DateTime>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pastes::Entity")]
    Pastes,
    #[sea_orm(has_many = "super::users_tokens::Entity")]
    UsersTokens,
}

impl Related<super::pastes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pastes.def()
    }
}

impl Related<super::users_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
